name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4  # Updated to v0.5.4
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Set up known hosts
        run: ssh-keyscan -H ${{ secrets.DO_IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Deploy to Digital Ocean
        run: |
          ssh root@${{ secrets.DO_IP_ADDRESS }} << 'EOF'
            # Check if the directory exists
            if [ ! -d /var/www/dublinstats ]; then
              echo "Directory does not exist. Creating it..."
              mkdir -p /var/www/dublinstats
            else
              echo "Directory already exists. Proceeding..."
            fi
            
            cd /var/www/dublinstats
      
            # Check if it's a Git repository
            if [ ! -d .git ]; then
              echo "Initializing Git repository..."
              git clone <your-repo-url> .
            else
              echo "Repository exists. Pulling latest changes..."
              git pull origin main
            fi
      
            # Install dependencies
            echo "Installing dependencies..."
            npm install
      
            # Restart or start the application
            echo "Restarting the application..."
            pm2 restart server.js || pm2 start server.js --name dublinstats
          EOF
